FROM apache/flink:2.2.1

USER root
# install python3 and pip3
RUN apt-get update -y && \
apt-get install -y python3 python3-pip python3-dev vim && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/python3 /usr/bin/python

# install PyFlink

RUN python -m pip install apache-flink uuid7 temporalio --break-system-packages
RUN python -m pip install apache-beam[gcp]  --break-system-packages
RUN python -m pip install jupyterlab  --break-system-packages

USER flink
