FROM apache/flink:latest

USER root
# install python3 and pip3
RUN apt-get update -y && \
apt-get install -y python3 python3-pip python3-dev vim && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/python3 /usr/bin/python

# install PyFlink

RUN python -m pip install apache-flink --break-system-packages
USER flink
